language: java
jdk:
  - openjdk8

# Travis CI를 어느 브랜치가 푸시될 때 수행할지 지정
# 현재 옵션은 오직 master 브랜치에 push될 때만 수행
branches:
  only:
    - master

# Travis CI 서버의 Home
# 그레이들을 통해 의존성을 받기 되면 이를 해당 디렉토리에 캐시하여
# 같은 의존성은 다음 배포 때 부터 다시 받지 않도록 설정함
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시되었을 때 수행하는 명령어
# 여기서는 프로젝트 내부에 둔 gradlew을 통해 clean & build를 수행
script: "./gradlew clean build"

# deploy 명령어가 실행되기 전에 수행됨
# CodeDeploy는 Jar 파일은 인식하지 못하므로 Jar+ 기타 설정 파일들을 모아 압축(zip) 한다
before_deploy:
  # 현재 위치의 모든 파일을 해당 이름으로 압축 명령어의 마지막 위치는 본인의 프로젝트 이름
  #- zip -r springboot-aws-impl-alone *
  # deploy라는 디렉토리를 Travis CI가 실행 중인 위치에서 생성
  #- mkdir -p deploy
  #- mv springboot-aws-impl-alone.zip deploy/springboot-aws-impl-alone.zip
  # Travis CI는 S3로 특정 파일만 업로드가 안됨
  # 디렉토리 단위로만 업로드할 수 있기 때문에 deploy 디렉토리는 항상 생성함
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  # before-deploy에는 zip 파일에 포함시킬 파일들을 저장한다
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  # zip -r 명령어를 통해 before-deploy 디렉토리 전체 파일을 압축한다
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/springboot-aws-impl-alone.zip # deploy로 zip파일 이동

#  AKIAYQADAJ6H5OSQUYA7
#  QrHVI8qY6Go8lUidG2i0I/JpH+k/PQ18qFZpmfs7
# S3로 파일 업로드 혹은 CodeDeploy로 배포 등 외부 서비스와 연동될 행위들을 선언
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: freelect-springboot-build1191 # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리 해당위치 파일들만 S3로 전송
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: freelect-springboot-build1191 # S3 버킷
    key: springboot-aws-impl-alone.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: springboot-aws-impl-alone # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: springboot-aws-impl-alone-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - freejava1191@gmail.com