# CodeDeploy 버전
# 프로젝트 버전이 아니므로 0.0외에 다른 버전을 사용하면 오류가 발생함
version: 0.0
os: linux
files:
    # CodeDeploy에서 전달해 준 파일 중 destination으로 이동 시킬 대상을 지정
    # 루트 경로(/)를 지정하면 전체 파일을 이야기 함
  - source:  /
    # source에서 지정된 파일을 받은 위치
    # 이후 Jar를 실행하는 등은 destination에서 옮긴 파일들로 진행됨
    destination: /home/ec2-user/app/step2/zip/
    # 기존에 파일들이 있으면 덮어쓸지 결정함
    # 현재 yes라고 했으니 파일을 덮어씀
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user
