spring:
  profiles:
    include: oauth
  session:
    # spring-session-jdbc 디펜던시 추가하고 설정시
    # JPA로 세션 테이블 자동 생성 설정
    store-type: jdbc
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
  h2:
    console:
      enabled: true