spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 638043754520-mk5bqp0t0q11himkh21n8tth111b0co5.apps.googleusercontent.com
            client-secret: WTIG-ty11RWOqvgw3Kv7p3Yq
            # openid라는 scope가 있으면 Open Id Provider로 인식함
            # 네이버/카카오등의 서비스는 Open Id Provider 가 아니라 기본설정으로 하면 각각 Oauth2Service를 만들어야함
            # 하나의 OAuth2Service로 사용하기 위해 일부러 openid scope를 빼고 등록
            scope: profile,email
          naver:
            client-name: Naver
            client-id: XjkOsAYTXunkRzQXNHHz
            client-secret: M7rXCcIBeE
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            # 네이버서는 response로 해야됨 이유는 네이버의 회원 조회 시 반환되는 JSON 형태 때문
            # 스프링 시큐리티에선 하위 필드를 명시할 수 없음
            # 네이버 최상위 필드 resultCode, message, response
            user-name-attribute: response