spring:
  jpa:
    show-sql: false
    hibernate:
      # 실제 운영에서는 절대 스프링 부트에서 테이블이 생성되지 않도록 해야됨
      ddl-auto: none
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://springboot-aws-impl-alone.caoklolkwzss.ap-northeast-2.rds.amazonaws.com:3306/springboot-aws-impl-alone
      username: admin
      password: 1879asdf
      driver-class-name: org.mariadb.jdbc.Driver